---
title: "Relatório_projeto_EPICOV"
author: "Matheus"
date: "21/08/2021"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r}
library(tidyverse)
library(readxl)
library(skimr)
df <- read_excel('../epicov_inicial.xlsx')
```

```{r Distribuição de sexo entre os paciente}
ggplot(data=df, aes(x=Sexo, y= (..count..)/sum(..count..)*100, fill=Sexo)) + 
  geom_bar() +
  ggtitle("Distribuição de sexo entre os pacientes") +
  labs(y="Quantidade de pacientes (%)")
```


```{r Descrição e análise da idade}

skim(df$Idade)

shapiro.test(df$Idade) # W = 0.98431, p-value = 2.025e-09

df %>% ggplot(aes())+
  geom_density(aes(Idade), fill="blue") # Left skewed
```

```{r Diferença de tempo entre início dos sintomas e internação hospiralar}
mean(df$`Data de admissão hospitalar no HC` - df$`Data do início dos sintomas`)/(24*60*60) # 8.38 dias de diferença
```

```{r Escala de coma de Glasgow na primeira hora de admissão na UTI}
skim(df$`Escala da Glasgow na primeira hora da admissão na UTI`)

shapiro.test(df$`Escala da Glasgow na primeira hora da admissão na UTI`)

ggplot(data=df, aes(x=`Escala da Glasgow na primeira hora da admissão na UTI`, y=(..count..)/sum(..count..)*100), fill="blue") +
  geom_bar() +
  labs(x="Escala de coma de Glasgow", y="Porcentagem de pacientes") +
  scale_x_continuous(name="Escala de coma de Glasgow", breaks=c(3, 6, 9, 12, 15), limits=c(2,16)) +
  scale_y_continuous(name="Porcentagem de pacientes", breaks=c(0, 10, 20, 30, 40, 50, 60))
```
