# Libraries usadas
library(tidyverse)
library(readxl)
library(skimr)
library(survival)
library(tinytex)
install.packages('tinytex')
install.packages("xfun")
tinytex::update_tinytex()
df <- read_excel("epicov_inicial.xlsx")
head(df)
